{{ config(materialized='view') }}

with incurred_diff_data as (

    select * from {{ref('incurred_load_view')}}
)

select PROJECT_ID,
	PACKAGE_TYPE,
	PACKAGE_SUBTYPE,
	PACKAGE,
	CBS_NAME,
	CBS_PATHID,
	CBS_STATUS,
	WPI_NUMBER,
	PO,
	COMMITMENT_ID,
	COMMITMENTS_AMT,
	ACTUALS_AMT,
	INCURRED_AMT,
	LAST_MONTH_INCURRED_AMT,
	INCURRED_TO_DATE,
	PRELIM_INCURRED_TO_DATE,
	(INCURRED_AMT - COMMITMENTS_AMT) AS DIFF_INCURRED_COMMITMENTS,
	(INCURRED_AMT - ACTUALS_AMT) AS DIFF_INCURRED_ACTUALS,
	CURRENT_MONTH_FORECAST,
	NULL AS IDENTIFIERS
from incurred_diff_data

